// <auto-generated />
namespace WorkoutHistoryApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenamedWorkouttabletoWorkoutItemtableUpdatedWorkoutItemtableCreatedWorkouttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedWorkouttabletoWorkoutItemtableUpdatedWorkoutItemtableCreatedWorkouttable));
        
        string IMigrationMetadata.Id
        {
            get { return "202302232130110_Renamed Workout table to WorkoutItem table, Updated WorkoutItem table, Created Workout table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
