// <auto-generated />
namespace WorkoutHistoryApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CretetablesExerciseTypeExerciseandWorkoutHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CretetablesExerciseTypeExerciseandWorkoutHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202302081928332_Crete tables ExerciseType, Exercise, and WorkoutHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
